name: Pull Request Auto Link

on:
  pull_request:
    types: [opened, labeled, closed]

jobs:
  add_label:
    name: Add Leabl
    runs-on: ubuntu-latest
    steps:
      - uses: timi137137/tdesign-pr-auto-link@main
