name: Pull Request Atuo Link

on: 
  pull_request: 
    types: closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: timi137137/tdesign-pr-auto-link@main
      - name: Run a one-line script
        run: echo Hello, world!
